# Configuración de Netlify

[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https: data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/dona"
  to = "/#donacion"
  status = 301

[[redirects]]
  from = "/centros"
  to = "/#centros"
  status = 301

[[redirects]]
  from = "/ayuda"
  to = "/#necesidades"
  status = 301